### ISSUE TITLE
Valid api_id must be provided. Can be obtained at https://my.telegram.org

### ISSUE THREAD

**Issue by jingming66** [Arman92/go-tdlib#110]
please help me,
I build flow : https://tdlib.github.io/td/build.html?language=Go first 
then go buid the example basicAuthorization.go

**Comment by isaquecsilva** [comment]
Same problem here. Did you find any workaround? I saw some posts informing that its caused by 1.8.0 tdlib version, as the data to be sent in the json should be inlined, or something like that.

A closed issue i found: [Error "Valid api_id must be provided" only on x64 #2211](https://github.com/tdlib/td/issues/2211)
